### ISSUE TITLE
Sarif Support 

### ISSUE THREAD

**Issue by frik0** [hands-lab/dockle-action#4]
Is there any chance for SARIF support (SARIF-compatible output file)? That would allow to use github/codeql-action/upload-sarif@v1 in workflows, Dockle already has support, but here in the GH Action not yet it would be nice to have it implemented.

**Comment by ndoell** [comment]
I'm trying this right now. I 've added a -f and -o option to the action.yml

```yaml
args:
    - '--exit-code=${{ inputs.exit-code }}'
    - '--exit-level=${{ inputs.exit-level }}'
    - '-f ${{ inputs.format }}'
    - '-o ${{ inputs.output }}'
    - '${{ inputs.image }}'
   ```

Then using it like:
```yaml
steps:
  - uses: hands-lab/dockle-action@v1
    with:
      image: hello-world
      format: 'sarif'
      output: 'dockle-image-results.sarif'
```
Only to get an error in the action.
```
"/github/workspace" goodwithtech/dockle:latest  "--exit-code=0" "--exit-level=WARN" "-f sarif" "-o dockle-image-results.sarif" "test-container"
Incorrect Usage. flag provided but not defined: -f sarif
```
